version: "3.3"
services:
  web:
    restart: unless-stopped
    build: .
    pull_policy: build
    # ports:
    #   - 8000:80
    volumes:
      - ./app:/app

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.wa-vs-http.rule=Host(`vs.wa.dtcloud.cz`)"
      - "traefik.http.routers.wa-vs-http.entrypoints=web"
      - "traefik.http.routers.wa-vs-http.middlewares=wa-vs-redirect-https@docker"

      - "traefik.http.middlewares.wa-vs-redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.wa-vs-redirect-https.redirectscheme.permanent=true"

      - "traefik.http.routers.wa-vs-https.rule=Host(`vs.wa.dtcloud.cz`)"
      - "traefik.http.routers.wa-vs-https.entrypoints=websecure"
      - "traefik.http.routers.wa-vs-https.tls=true"
      - "traefik.http.routers.wa-vs-https.tls.certresolver=letsencrypt"

  static:
    image: nginx:alpine
    restart: unless-stopped

    volumes:
      - ./app/static:/usr/share/nginx/html/static:ro

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.wa-vs-static-http.rule=Host(`vs.wa.dtcloud.cz`) && PathPrefix(`/static`)"
      - "traefik.http.routers.wa-vs-static-http.entrypoints=web"
      - "traefik.http.routers.wa-vs-static-http.middlewares=wa-vs-static-redirect-https@docker"

      - "traefik.http.middlewares.wa-vs-static-redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.wa-vs-static-redirect-https.redirectscheme.permanent=true"

      - "traefik.http.routers.wa-vs-static-https.rule=Host(`vs.wa.dtcloud.cz`) && PathPrefix(`/static`)"
      - "traefik.http.routers.wa-vs-static-https.entrypoints=websecure"
      - "traefik.http.routers.wa-vs-static-https.tls=true"
      - "traefik.http.routers.wa-vs-static-https.tls.certresolver=letsencrypt"

    networks:
      - default

networks:
  default:
    name: gateway
    external: true